function validateLuau(scriptText) {
  const stack = [];
  const pairs = { ')': '(', '}': '{', ']': '[' };
  let openSingle = false;
  let openDouble = false;

  const lines = scriptText.split('\n');
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    for (let char of line) {
      if (char === '"' && !openSingle) openDouble = !openDouble;
      else if (char === "'" && !openDouble) openSingle = !openSingle;
      else if (!openSingle && !openDouble) {
        if (Object.values(pairs).includes(char)) {
          stack.push(char);
        } else if (Object.keys(pairs).includes(char)) {
          if (stack.length === 0 || stack[stack.length - 1] !== pairs[char]) {
            return { valid: false, error: `Syntax Error: Unmatched '${char}' near line ${i + 1}` };
          }
          stack.pop();
        }
      }
    }
  }
  if (stack.length > 0) {
    return { valid: false, error: `Syntax Error: Unclosed bracket '${stack[stack.length - 1]}'` };
  }
  return { valid: true };
}

exports.handler = async (event, context) => {
  if (event.httpMethod !== "POST") return { statusCode: 405, body: "Method Not Allowed" };

  try {
    const { code, filename = "script.luau" } = JSON.parse(event.body || "{}");

    if (!code || !code.trim()) {
      return { statusCode: 400, body: JSON.stringify({ success: false, error: "Script cannot be empty." }) };
    }

    const validation = validateLuau(code);
    if (!validation.valid) {
      return { statusCode: 422, body: JSON.stringify({ success: false, error: validation.error }) };
    }

    const timestamp = new Date().toISOString().replace('T', ' ').substring(0, 19) + ' UTC';
    const header = `-- vm dex\n-- Generated by VMdex Engine v1.0.0\n-- Processed at: ${timestamp}\n\n`;
    
    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ success: true, filename, obfuscated_code: header + code })
    };
  } catch (err) {
    return { statusCode: 500, body: JSON.stringify({ success: false, error: "Server Error" }) };
  }
};
